### ISSUE TITLE
request a rss feed in your blog

### ISSUE THREAD

**Issue by 0915240** [zqhxuyuan/zqhxuyuan.github.io#1]
some article in your blog is amazing .  i want to subscribe your blog but i can not find a rss feed in your blog .

so do please add a rss feed in your blog like :
`http://zqhxuyuan.github.io/atom.xml`  or  `http://zqhxuyuan.github.io/feed`

thx ~ :+1:

**Comment by zqhxuyuan** [comment]
add atom in my blog: http://zqhxuyuan.github.io/atom.xml
tks for your following
